### ISSUE TITLE
Cache TTL doesn't seem to work

### ISSUE THREAD

**Issue by bpb27** [cvburgess/SQLDataSource#12]
Hey thanks for this package!

I'm running v0.1.4 and noticed that when using `getBatchedAndCached`, passing a TTL doesn't do anything, and the set value seems to live in the cache forever. I tried:

```js
getBatchedAndCached(query, 1);
getBatchedAndCached(query, 0);
getBatchedAndCached(query, -1);
getBatchedAndCached(query, { ttl: 0 });
```

I think the issue might be that `apollo-server-caching@0.1.2` doesn't actually use a TTL in `set`.

```js
class InMemoryLRUCache {
  constructor({ maxSize = Infinity } = {}) {
    this.store = LRU({ max: maxSize, length: item => item.length });
  }
  get(key) {
    return __awaiter(this, void 0, void 0, function* () {
      return this.store.get(key);
    });
  }
  set(key, value) {
    return __awaiter(this, void 0, void 0, function* () {
      this.store.set(key, value);
    });
  }
}
```

I can get around it by installing `apollo-server-caching@0.3.1` and passing in `{ cache: new InMemoryLRUCache() }` in `initialize`.

Not sure if I'm missing something, but I think you can just update the dependency.

**Comment by cvburgess** [comment]
Thank you so much! This has been bugging me but I have not had time to dive in.

**Comment by cvburgess** [comment]
https://github.com/cvburgess/SQLDataSource/releases/tag/v0.1.5 Should resolve the cache TTL issue.

CC: @tab00

**Comment by bpb27** [comment]
Thanks! Confirmed that it's fixed. 🎉

Might want to update the README example:

```
const MINUTE = { ttl: 60 };
```

The Apollo package looks for a `ttl` prop in an options object and multiplies the number by 1000.

**Comment by cvburgess** [comment]
Oh thats great to know - would you mind opening a PR for that?
