### ISSUE TITLE
Fix ttl

### ISSUE THREAD

**Issue by lorensr** [cvburgess/SQLDataSource#15]
https://github.com/cvburgess/SQLDataSource/blob/master/SQLCache.js#L24-L40

Last param to `.set` is an object:

https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-caching#implementing-your-own-cache

Also, ttl is in seconds, so example in README shouldn't multiply by 1000

**Comment by cvburgess** [comment]
Yup, see the discussion on #12 

Please feel free to open a PR - or i will try to get to it as soon as possible.

**Comment by cvburgess** [comment]
Does this PR fix your issue @lorensr https://github.com/cvburgess/SQLDataSource/pull/16 ?

**Comment by cvburgess** [comment]
Released to NPM https://github.com/cvburgess/SQLDataSource/releases/tag/v0.1.6
