### ISSUE TITLE
Redis cache

### ISSUE THREAD

**Issue by Redirts** [cvburgess/SQLDataSource#17]
I want to Redis for caching but it does not seem to be working. Without redis caching specified it works fine (InMemoryLRUCache).

What I did was:

import { RedisCache } from 'apollo-server-cache-redis';

//passed to ApolloServer setup:

  cache: new RedisCache({
    host: 'localhost',
    port: 6379
  }),

then I am caching with getBatchedAndCached(knexquery)

When I run it I am getting these errors:

node_redis: Deprecated: The SET command contains a argument of type Object.
This is converted to "[object Object]" by using .toString() now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
...
 error: uncaughtException: ERR syntax error
ReplyError: ERR syntax error
    at parseError (C:\Users\Tiago Alcobia\Documents\crossviewer-services\v2-query-service\node_modules\redis-parser\lib\parser.js:193:12)
    at parseType (C:\Users\Tiago Alcobia\Documents\crossviewer-services\v2-query-service\node_modules\redis-parser\lib\parser.js:303:14)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by cvburgess** [comment]
Hmm this is no bueno - what version of apollo are you using?

**Comment by cvburgess** [comment]
We swtiched to an object in this PR https://github.com/cvburgess/SQLDataSource/pull/16

**Comment by Redirts** [comment]
Taken directly from my package.json:

    "apollo-server": "^2.4.8",
    "apollo-server-express": "^2.4.8",

**Comment by cvburgess** [comment]
This should be working, especially in v1 - please reopen if I am wrong!
