### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by lorensr** [cvburgess/SQLDataSource#20]
For example:

https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L117-L141

and a method to override:

https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L100-L102

(I'm not asking for this feature for myself—just a suggestion for future dev ☺️)

**Comment by cvburgess** [comment]
Interesting idea! Thanks for the ticket

**Comment by cvburgess** [comment]
This should be fine with v1, as we are not changing or wrapping knex anymore. Any .catch(_ should suffice!
