### ISSUE TITLE
Support for multiple loggers

### ISSUE THREAD

**Issue by Redirts** [cvburgess/SQLDataSource#21]
The change made in #5 is not compatible with multiple datasources.
We are using two knex instances (2 DB's) in our project.

Since the variable hasLogger is not a class/object property it will be set true for the first object (knex instance) and will not be initialized for the following ones since hasLogger is already true.

**Comment by cvburgess** [comment]
thank you! Please open a PR, or hang tight - it may take me several days to get to this

**Comment by cvburgess** [comment]
Is this fixed in v1 for you? we now create the Knex object in the constructor.

**Comment by Redirts** [comment]
Hi,

In the meanwhile I stopped using SQLDataSource so I cannot test it anymore unfortunately...
