### ISSUE TITLE
What if the instance of database is created asynchronously?

### ISSUE THREAD

**Issue by mrdulin** [cvburgess/SQLDataSource#22]
For example, create the instance of DB connection asynchronously.

```ts
constructor() {
    super();
    // Add your instance of db to the DataSource
    // this.knex = await createKnex()
  }
```

How can I do this?

**Comment by cvburgess** [comment]
Hmmm - I have not really put much thought into that because most apps create a single connection and pool to it at startup (from my experience). If you can think of a solution, please open a PR :)

**Comment by tortillaj** [comment]
@mrdulin - I have a similar situation that might help. We fetch database credentials from AWS SSM before starting the node server. That way they're available to Apollo datasources. 

```
const app = express()

getRemoteCredentials()
    .then(creds => {
        const apollo = new ApolloServer({
            ...
            dataSources: () => {
                // you have credentials here to make a knex client as needed

                return {
                    .....
                }
            },
        })

        app.listen( .......... )
    })

```

**Comment by cvburgess** [comment]
This seems solveable outside this repo, thank you for the help @tortillaj
