### ISSUE TITLE
unpin node version?

### ISSUE THREAD

**Issue by jakelowen** [cvburgess/SQLDataSource#3]
Great package! Thanks.

Is there any particular reason you've pinned your node engine at 10.6.0?
I'm currently developing on 11.1.0 and when I install this package I get a warning: 

```
error datasource-sql@0.1.2: The engine "node" is incompatible with this module. Expected version "10.6.0". Got "11.1.0"
error Found incompatible module
```

It would be great to avoid that warning on an install.

**Comment by cvburgess** [comment]
Nope! I should probably change it to >= 10.x based on node.green

**Comment by cvburgess** [comment]
@jakelowen does https://github.com/cvburgess/SQLDataSource/pull/4 fix your issue?

**Comment by cvburgess** [comment]
@jakelowen v0.1.3 is published - hope it helps!
