### ISSUE TITLE
not work with memcached or redis

### ISSUE THREAD

**Issue by BoryaMogila** [cvburgess/SQLDataSource#31]
key for memcached or redis must by without spaces
Error: The key should not contain any whitespace or new lines

**Comment by cvburgess** [comment]
Thank you - there was a PR open to fix as much, let me look into this

**Comment by cvburgess** [comment]
Tested locally with Redis and not having any issues. Can i get more information please?

**Comment by cvburgess** [comment]
Please see if v1.0.1 fixes your issue!

**Comment by BoryaMogila** [comment]
Thanks, now work.
