### ISSUE TITLE
Where to destroy the database connection

### ISSUE THREAD

**Issue by iaarab** [cvburgess/SQLDataSource#35]
Hi

What is the best place to destroy the database connection?

This is what i have now but it doesn't work:
![image](https://user-images.githubusercontent.com/38687515/65761240-b4cb4680-e11e-11e9-9796-30c32f44232c.png)

![image](https://user-images.githubusercontent.com/38687515/65761567-4e92f380-e11f-11e9-8910-007352905227.png)

The problem is that i get `"message": "Unable to acquire a connection"` on every request.

**Comment by cvburgess** [comment]
Do you not use a database with pooling? Managing your own connections is usually not recommended. You can configure pooling in the knex config object.

**Comment by cvburgess** [comment]
Also it looks like you are using an older version of this lib. In v1 the format is different which may explain it not connecting. Check out the readme for more information!

**Comment by sesteva** [comment]
I'm using this with oracledb and it looks like the pool connection keeps the event loop busy and so the process does not exit. 
I'm especially concern about this as I will be executing within an AWS lambda.
After discussing with the guys behind oracledb module, I was suggested to close the pool when the SIGTERM/SIGINT signals are issued.

I do this where I create the datasources.

```
const Clients = require("./clients");
const OracleAnalytics = require("./oracle-analytics");

const Oracle = new OracleAnalytics();

const dataSources = () => ({
  clients: new Clients(),
  oracleAnalytics: Oracle
});

module.exports = dataSources;

async function closePoolAndExit() {
  try {
    await Oracle.db.destroy();
    console.log("Pool closed");
    process.exit(0);
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
}

process.once("SIGTERM", closePoolAndExit).once("SIGINT", closePoolAndExit);

```

Here is the thread about oracledb [Github Thread](https://github.com/oracle/node-oracledb/issues/1174)

**Comment by cvburgess** [comment]
Note, please use the KNEX documentation for pooling, this is merely a thin wrapper on top of KNEX.
