### ISSUE TITLE
Add DataLoader

### ISSUE THREAD

**Issue by lorensr** [cvburgess/SQLDataSource#42]
For batching and deduplication.

**Comment by cvburgess** [comment]
This lib used to use dataloader for batching and deduping and it just does not play well with knex.

**Comment by sebas5384** [comment]
@cvburgess could you elaborate a bit more on why doesn't play well with knex? and how are you resolving the N+1 problem?

Reference: https://github.com/graphql/dataloader/blob/master/examples/Knex.md

**Comment by cvburgess** [comment]
Of course!

Notice how each one of those is specialized and essentially changes the underlying SQL query?

Thats not something i can or want to easily do under the hood when there is nothing stopping you from still doing it in userland.

You CAN add dataloader on top of this lib, but i cannot easily add it without stringifying queries and running them with .raw ( which is how this lib used to do it, go look at the source pre 1.0 ).

**Comment by sebas5384** [comment]
gotcha! thanks for the explanation @cvburgess 👍
