### ISSUE TITLE
Save knex instance to this.knex instead of this.db

### ISSUE THREAD

**Issue by lorensr** [cvburgess/SQLDataSource#43]
In order to:
- avoid confusion between having multiple `db`s: `dataSources.db.*` in resolvers and `this.db.*` in data source
- more closely match knex docs (which say eg `knex.select().from('users')`), so we'd do 

`this.knex.select().from('users')` 
instead of 
`this.db.select().from('users')`

https://github.com/cvburgess/SQLDataSource/blob/master/index.js#L17

**Comment by lorensr** [comment]
(could be back compat by just adding the line `this.knex = this.db`)

**Comment by cvburgess** [comment]
That is actually how this lib used to work, I dont have a strong objection to this if you want to open a PR :)

**Comment by lorensr** [comment]
Implemented in #44
