### ISSUE TITLE
Allow constructor to take a knex instance

### ISSUE THREAD

**Issue by lorensr** [cvburgess/SQLDataSource#46]
Instead of just `knexConfig`. This way knex can be used outside of the data source. (Knex recommends a single instance per server.)

**Comment by cvburgess** [comment]
Hmmm the data source exports a knex instance you can use - have you tried that?

**Comment by cvburgess** [comment]
For what its worth, i support this if you want to open a PR and update the docs.

**Comment by lorensr** [comment]
Closed by #52
