### ISSUE TITLE
Support provided cacheKey

### ISSUE THREAD

**Issue by mwhipple** [cvburgess/SQLDataSource#54]
I'm looking to support a customizable cache key strategy. It seems like a simple approach would just be to support an optional cacheKey parameter to `cacheQuery` (and the builder `cache` method) and only use the currently generated approach if the parameter is not provided. Thoughts?

**Comment by cvburgess** [comment]
Seems fine to me - please open a PR!

**Comment by cvburgess** [comment]
@mwhipple I will go ahead and close this, assuming you are not going to open a PR.

If you decide to open the PR, I will re-open the issue!
