### ISSUE TITLE
Examples for parameterized queries and mutations

### ISSUE THREAD

**Issue by gordonbazeley** [cvburgess/SQLDataSource#55]
Hi there,
  I'm new to GraphQL and have spent most of today trying to get MySQL database working.  So far I have unbounded queries working but can't for the life of me work out how to pass parameters in for creating a row or querying an individual row - would it be possible to provide some examples for an idiot please?

Many thanks ...

**Comment by cvburgess** [comment]
This is a tiny wrapper over knexjs.org - have a look over there, they have great docs on all these things!
