### ISSUE TITLE
How to implement Aggregation?

### ISSUE THREAD

**Issue by AnderUstarroz** [cvburgess/SQLDataSource#58]
If the schemas are statically defined[ how could we use aggregation with knex](https://stackoverflow.com/questions/63231094/how-to-implement-aggregation-on-apollo-graphql-server)?
For instance the following query:
`SELECT count(*) AS column1, MAX(Id) AS column2 FROM some_table`

**Comment by cvburgess** [comment]
This may be a better question for Knex? This library only acts as a thin wrapper with a cache so I unfortunately don't have an answer for you.

**Comment by cvburgess** [comment]
Fwiw you can write any query you want in KNEX using `.raw` but they do support a wide range of features.
