### ISSUE TITLE
Peer version of graph-ql set to ^14.0.2" 

### ISSUE THREAD

**Issue by korbav** [cvburgess/SQLDataSource#64]
Hello, I'm trying to update SQLDataSource to its last version but it seems the peer dependency is blocking the usage with graphql@^15.5.0

```
 "peerDependencies": {
    "graphql": "^14.0.2"
  },
```

Error message : `ERESOLVE unable to resolve dependency tree Found: graphql@15.5.0.. peer graphql@"^14.0.2" from datasource-sql@1.4.0`

Is this version restriction intended?

**Comment by matteoredaelli** [comment]
Same issue for me

**Comment by cvburgess** [comment]
Thanks, will resolve this
