### ISSUE TITLE
Knex types is broken in 1.6.0

### ISSUE THREAD

**Issue by Luchanso** [cvburgess/SQLDataSource#71]
Example: https://codesandbox.io/s/strange-austin-2ccpm?file=/src/index.ts

I think this happen after knex moved in peerDependencies - my project start using latest version of knex (0.95.x), but before SQLDataSource using types from 0.21.x

I guess between 0.21.x and 0.95.x changed export typings on naming exports:
`import knex from 'knex'` ->  `import { knex } from 'knex'`,  but if you do this fix, you can broke projects with older version of knex

**Comment by Luchanso** [comment]
One of solution, make breaking change version SQLDataSource for newer knex version

**Comment by Luchanso** [comment]
Fix: https://github.com/Luchanso/SQLDataSource/commit/e0211d008b13ec244e0b42ae4b6f0bb2c650ee01 it was helped for my project

**Comment by cvburgess** [comment]
Hmm i think theres a way to do this without breaking anything by checking the default export for a Knex property.

Need to write some code to confirm but I personally don't use this project much anymore as I have stated in other issues so @Luchanso if you could add a working example I could test against, I can release a v1.6.1.

**Comment by Luchanso** [comment]
https://codesandbox.io/s/typescript-node-sql-db-b76f4?file=/src/index.ts
If you want check changes, you need restart server (tab Server Control Panel in left sidebar) in sandbox manually (hot reload not working)

And[ I tested my fix](https://codesandbox.io/s/typescript-node-sql-db-forked-teo5m?file=/src/index.ts) with old knex version - it's breaking project typings

**Comment by Luchanso** [comment]
I'll try write type which pick not any type, something like this:
```ts
import KnexDefault, { Knex as KnexNaming } from "knex";

type PickNotAnyType<T1, T2> = ???; // 🤔

type Knex = PickNotAnyType<KnexDefault, KnexNaming>;
```

**Comment by Luchanso** [comment]
I think it's unreal, because `any` include all other types, maybe exist other solution...

**Comment by cvburgess** [comment]
You are close, but i think you need to implement it like so in index.js of sql-datasource:

```js
const knexImport = require("knex");

const Knex = knexImport?.Knex || knexImport?.default || knexImport;
```

If there is a `.default` exported from the old versions of Knex, you can delete ` || knexImport;`, if not, delete`|| knexImport?.default` instead.

Let me know if this works and we can merge it into a 1.6.1 release!

**Comment by davidwoodmansee** [comment]
a temporary workaround for me was to add the following to my tsconfig. I think the suggestion above is close but you also need a fix for index.d.ts and I wasn't able to get through that part
```
{
  "compilerOptions": {
    "skipLibCheck": true,
    }
}
```

**Comment by Luchanso** [comment]
@cvburgess I tried this and couldn't find a solution

**Comment by cvburgess** [comment]
i do not personally use TS so I can't assist much further on this, unfortunately.

I will leave the issue open and hopefully someone that uses TS will hit the issue and volunteer to correct the types in a backward-compatible way.

**Comment by Luchanso** [comment]
Okey, if anyone need using latest knex and SQLDataSource, you can use workaround solution: `npm i @luchanso/datasource-sql`, but this package not capability with older version of knex

**Comment by grusite** [comment]
Hey! I am having the same issue and I think a lot more will have. I created a PR to update the Knex import. @cvburgess can you please make a new version with this?

Regarding backward-compatibility the ones who is using previous versions of Knex, will need to also use your previous version (up to 1.6.0). In case they want the latest version of SLQDataSource, they will need to install the latest version of knex also.

Thanks!

**Comment by cvburgess** [comment]
This is now live in v2.0.0

If you are not ready to move to Knex v0.95+, stay on the 1.x version of this library.

That said, I don't anticipate maintaining 1.x unless there is a critical security issue.

Thanks for the PR @grusite !
