### ISSUE TITLE
SET Postgres run-time configuration parameters

### ISSUE THREAD

**Issue by UserRand42** [cvburgess/SQLDataSource#79]
Is there a way to dynamically set/reset custom Postgres run-time configuration parameters?

I have tried to set a custom parameter using the pool "afterCreate" event, in the api definition, with:

getData(value) {

this.knex.client.pool.on('createSuccess', (eventId, resource) => {
  resource.query("SET custom\.param = '" + value+ "'", () => {})
});
const res = this.knex
      .from("table")
      .select()
      .limit(count)
      .cache(MINUTE);
console.log(res);
return res;
}

This works once, but the parameter could not be updated after the first query. 

I have also tried to use "raw" but without success:

const res = this.knex.raw("SET custom\.param = 'actual_value'; SELECT \* FROM table limit 10; RESET custom\.param;")
      .then((result) => {
      })
      .catch((error) => {
      });
console.log(res);
return res;

**Comment by cvburgess** [comment]
I think this is specific to Knex and not this library. Have you tried opening an issue in the repo?

**Comment by UserRand42** [comment]
Thank you for the quick reply.  It's not complete as I was not able to RESET the parameter, but I was able to SET a parameter with:

return this.knex
      .raw("SET custom\.param = 'actual_value';")
      .then(() => {
        return this.knex.select().from("table").limit(10).cache(MINUTE);
      });
